import numpy as np

# BASIC OPERATIONS USING NUMPY!!!

# LOS OPERADORES ARITMETICOS EN NUMPY SE APLICAN UNO POR UNO A CADA ELEMENTO DEL ARREGLO


arrA = np.array([0, 10, 20, 30, 40])

arrB = np.arange(0, 10, 2)


print('El arreglo A: \n', arrA)

print('El arreglo B: \n', arrB)


# RESTA

print(arrA - arrB)

# MULTIPLICACION POR UN ESCALAR

print(arrA * 2)

# COMPARACION BOOLEANA

arrC = arrA < 20

print(arrA[arrC])  # IMPORTANTE ESTAMOS GENERANDO UNA MASCARA BOOLEANA

# OTROS TIPOS DE OPERACIONES IMPORTANTES CUANDO ESTAMOS TRABAJANDO CON ARREGLOS

#       PRODUCTO PUNTO DE UN ARREGLO O MATRIZ:

arrDot = arrA @ arrB

print(arrDot)


# WHEN USING "+=" OR "*=" THESE OPERATORS MODIFY DE ORIGINAL ARRAY INSTEAD OF CREATING A NEW ONE
